apiVersion: 1

datasources:
  - name: Loki QA
    type: loki
    access: proxy
    url: http://loki-qa:3100
    isDefault: true
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - matcherRegex: 'requestId["\s:]+([a-f0-9-]+)'
          name: RequestID
          url: '#'
