version: '3.8'

services:
  workshop_db:
    container_name: workshop-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - workshop-network

  workshop_spring_app:
    container_name: workshop-api
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - workshop_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://workshop-db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: production
      JAVA_TOOL_OPTIONS: "-Xms256m -Xmx768m"
    networks:
      - workshop-network

volumes:
  db_data:

networks:
  workshop-network:
