app:
  version: '@project.version@'

spring:
  profiles:
    active: local

  datasource:
    hikari:
      connection-init-sql: SET pg_trgm.word_similarity_threshold TO 0.45

  jpa:
    open-in-view: false
    hibernate:
      default_schema: public
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.temp.use_jdbc_metadata_defaults: false

server:
  compression:
    enabled: true
  port: 8080
  servlet:
    session:
      timeout: 30