spring:
  profiles:
    active: local

  jpa:
    hibernate:
      default_schema: public
      ddl-auto: validate
#      allow camel case names on entities
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.temp.use_jdbc_metadata_defaults: false

server:
  compression:
    enabled: true
  port: 8080
  sessionTimeout: 30