[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=4
repo1-retention-diff=14
start-fast=y
log-level-console=info
log-level-file=info
log-path=/var/log/pgbackrest

[workshop]
pg1-path=/var/lib/postgresql/data
pg1-port=5432
pg1-user=DB_USER_PLACEHOLDER
