-- Fix typo corrections on brands
WITH updated_brand_name (id, new_name) AS (
    VALUES
     (334,'3 corações'),
	 (382,'3 corações'),
	 (186,'acer'),
	 (204,'afra'),
	 (196,'agratto'),
	 (226,'air fryer'),
	 (379,'altez'),
	 (279,'american pro'),
	 (386,'amvoz'),
	 (240,'and'), 
	 (195,'angle grinder'),
	 (396,'anodilar'),
	 (169,'antiga'),
	 (87,'arge'),
	 (78,'arke'),
	 (2,'arno'),
	 (324,'arno'),
	 (166,'arno'),
	 (354,'art'),
	 (288,'atlanta'),
	 (122,'atlas'),
	 (74,'awt'),
	 (368,'babyliss'),
	 (24,'babyliss'),
	 (200,'babyliss pro'),
	 (43,'babyliss pro'),
	 (291,'bee eletrics'),
	 (406,'bel'),
	 (309,'bella'),
	 (315,'beltec'),
	 (99,'best'),
	 (393,'bigolar'),
	 (192,'bioterm'),
	 (335,'biovis'),
	 (3,'black & decker'),
	 (260,'bluskey'),
	 (243,'bonus'),
	 (30,'bosch'),
	 (7,'brastemp'),
	 (129,'braum'),
	 (389,'braun'),
	 (202,'brisa'),
	 (56,'britânia'),
	 (269,'britânia'),
	 (367,'britânia'),
	 (8,'britânia'),
	 (233,'britânia'),
	 (101,'brocks'),
	 (263,'cabo pp'),
	 (32,'cadence'),
	 (349,'cadence'),
	 (304,'karcher'),
	 (197,'cce'),
	 (159,'certec'),
	 (327,'cetro'),
	 (144,'chain saw'),
	 (52,'chiaperini'),
	 (376,'churrasqueira'),
	 (356,'cid'),
	 (150,'cinhell'),
	 (100,'colormaq'),
	 (115,'colorvisão'),
	 (123,'conair'),
	 (130,'confilar'),
	 (5,'consul'),
	 (124,'consul'),
	 (71,'continental'),
	 (308,'cool and hot'),
	 (273,'cortag'),
	 (337,'cuisinart'),
	 (392,'cuisinart'),
	 (280,'cuisinart'),
	 (326,'cuisinart'),
	 (242,'cuisinart'),
	 (64,'daevoo'),
	 (134,'daewoo'),
	 (401,'dako'),
	 (241,'dayhatsu'),
	 (154,'dellano'),
	 (357,'dellar'),
	 (31,'delta'),
	 (117,'delta'),
	 (131,'delta premiun'),
	 (188,'dewalt'),
	 (37,'dewalt'),
	 (77,'digitron'),
	 (189,'diversas'),
	 (21,'doltom'),
	 (65,'domina'),
	 (59,'durabrand'),
	 (102,'dewalt'),
	 (70,'dewalt'),
	 (179,'dewalt tipo2'),
	 (300,'dwt'),
	 (227,'eco'),
	 (181,'ecofer'),
	 (297,'einhell'),
	 (276,'electric'),
	 (6,'electrolux'),
	 (329,'electrolux'),
	 (271,'electroux'),
	 (72,'eletrolux'),
	 (278,'elgin'),
	 (163,'elloo'),
	 (302,'energy'),
	 (388,'eos'),
	 (307,'espetosul'),
	 (286,'euro'),
	 (342,'everest'),
	 (107,'faet'),
	 (39,'fama'),
	 (249,'fat grill machine'),
	 (90,'fischer'),
	 (120,'fischer de embutir'),
	 (366,'fischer'),
	 (293,'fiolux'),
	 (27,'fischer'),
	 (146,'fischer'),
	 (348,'fischer'),
	 (217,'fischer'),
	 (203,'fix'),
	 (93,'fogatti'),
	 (108,'force line'),
	 (151,'fortec'),
	 (69,'free home'),
	 (306,'fritadeira'),
	 (40,'frontec'),
	 (361,'fsatam'),
	 (75,'fun kitchen'),
	 (239,'fun kitchen'),
	 (359,'futura'),
	 (173,'g.tec'),
	 (328,'gaabor'),
	 (18,'gama'),
	 (338,'gama'),
	 (339,'gama'),
	 (317,'gamma'),
	 (358,'garden'),
	 (364,'garthen'),
	 (136,'garthen'),
	 (222,'gastromaq'),
	 (231,'ge'),
	 (267,'gecaldi'),
	 (405,'general eletric'),
	 (139,'george foreman'),
	 (344,'george foreman'),
	 (230,'goar'),
	 (178,'goldstar'),
	 (253,'gomes inox'),
	 (256,'gotto'),
	 (25,'gtech'),
	 (220,'gtech'),
	 (238,'gural'),
	 (73,'h2omop'),
	 (277,'haier'),
	 (395,'hair style'),
	 (363,'hairliss'),
	 (103,'hamilton beach'),
	 (391,'air cooler'),
	 (126,'hidra'),
	 (97,'hoier'),
	 (214,'home free'),
	 (320,'home gyn'),
	 (219,'home life'),
	 (296,'honeywell'),
	 (88,'hongda'),
	 (55,'hoss'),
	 (282,'hoster'),
	 (283,'hoster'),
	 (182,'househoud'),
	 (394,'htm'),
	 (360,'ibbl'),
	 (374,'ibramed'),
	 (224,'ika c mag'),
	 (58,'importado'),
	 (135,'importway'),
	 (167,'industrial'),
	 (274,'infantil'),
	 (380,'ingco'),
	 (397,'ipc'),
	 (305,'james'),
	 (232,'japonesa'),
	 (381,'kacil'),
	 (375,'karcher'),
	 (92,'kayomi'),
	 (259,'kdeletro'),
	 (316,'kerigma'),
	 (143,'kiss'),
	 (330,'knup'),
	 (261,'krain'),
	 (353,'ks'),
	 (365,'labstore'),
	 (402,'lair'),
	 (378,'lancheira'),
	 (112,'latina'),
	 (272,'lava home'),
	 (215,'lavadora'),
	 (199,'lavor'),
	 (172,'layr'),
	 (145,'leão tools'),
	 (275,'led'),
	 (164,'lenoxx'),
	 (4,'lg'),
	 (149,'libel'),
	 (257,'lith'),
	 (187,'lizze'),
	 (403,'lizzy'),
	 (94,'longda'),
	 (183,'loreal'),
	 (153,'loren sid'),
	 (137,'lorenzetti'),
	 (106,'lorenzetti'),
	 (35,'lorenzetti'),
	 (404,'lorenzetti'),
	 (372,'electrolux'),
	 (218,'lt'),
	 (162,'luxor'),
	 (28,'macaco'),
	 (268,'madeira'),
	 (44,'magna'),
	 (16,'makita'),
	 (63,'mallory'),
	 (208,'mallory'),
	 (198,'malta'),
	 (113,'marchesoni'),
	 (194,'marchesoni'),
	 (262,'margirius'),
	 (246,'marinex'),
	 (340,'martau'),
	 (50,'master'),
	 (314,'masterchef'),
	 (301,'master frio'),
	 (207,'maxis'),
	 (61,'maxon'),
	 (121,'mega'),
	 (191,'mega bell'),
	 (250,'mega bell'),
	 (38,'mega star'),
	 (266,'mega star'),
	 (80,'midea'),
	 (104,'menegotti'),
	 (85,'metabo'),
	 (345,'metalcubas'),
	 (49,'mi aroma'),
	 (341,'midas'),
	 (33,'midea'),
	 (76,'midea/liva'),
	 (158,'midea'),
	 (331,'midi'),
	 (47,'mitsuo'),
	 (114,'mm'),
	 (14,'mondial'),
	 (156,'motormil'),
	 (180,'mq titanium'),
	 (119,'mueller'),
	 (17,'mueller'),
	 (369,'multi home'),
	 (9,'multi-sec'),
	 (312,'multilador'),
	 (133,'multilaser'),
	 (244,'my kat'),
	 (132,'nardelli'),
	 (185,'national'),
	 (377,'nativa'),
	 (190,'nell'),
	 (322,'nespresso'),
	 (118,'new maq'),
	 (26,'nilko'),
	 (155,'nks'),
	 (141,'ns'),
	 (318,'hair steamer'),
	 (265,'olira'),
	 (111,'onida'),
	 (48,'oster'),
	 (251,'ouro inteligente'),
	 (400,'ozozmini'),
	 (54,'panasonic'),
	 (67,'panter'),
	 (138,'parana'),
	 (319,'parise'),
	 (210,'parlux'),
	 (229,'power pet'),
	 (184,'powerpack'),
	 (385,'pelonis'),
	 (399,'peme'),
	 (161,'pg brush'),
	 (1,'philco'),
	 (171,'philco'),
	 (351,'philco'),
	 (12,'philips'),
	 (79,'philips walita'),
	 (96,'philips walita'),
	 (84,'phisiomax'),
	 (384,'pinheiro máquinas'),
	 (213,'powerpack'),
	 (247,'powerpack'),
	 (281,'powerpack'),
	 (176,'prax'),
	 (270,'praxxis'),
	 (287,'praxxis'),
	 (201,'princes'),
	 (23,'professional'),
	 (223,'profild'),
	 (128,'prosper'),
	 (152,'quanta'),
	 (303,'rebecca'),
	 (294,'relax'),
	 (352,'relax medic'),
	 (264,'remington'),
	 (343,'revlon'),
	 (29,'sem marca'),
	 (41,'sem marca'),
	 (165,'sem marca'),
	 (310,'sem marca'),
	 (15,'samsung'),
	 (157,'samsung'),
	 (245,'santa clara'),
	 (298,'santeg'),
	 (10,'sanyo'),
	 (57,'sate'),
	 (89,'satellite '),
	 (292,'satellite '),
	 (168,'schulz'),
	 (211,'sega'),
	 (237,'sega tolls'),
	 (98,'sem marca'),
	 (142,'setga'),
	 (398,'shark'),
	 (125,'sharp'),
	 (175,'shulz'),
	 (313,'silver steamer'),
	 (193,'singer'),
	 (206,'li einhell'),
	 (170,'sjs'),
	 (68,'skill'),
	 (355,'skillsaw'),
	 (252,'skinsen'),
	 (350,'skillsaw'),
	 (332,'skymsen'),
	 (333,'solaster'),
	 (235,'sonar'),
	 (346,'songhe'),
	 (383,'sony'),
	 (62,'sovar'),
	 (254,'speed'),
	 (336,'spidem'),
	 (258,'spolu'),
	 (387,'springer'),
	 (45,'stanley'),
	 (216,'starfrit'),
	 (311,'steamer paraiso'),
	 (46,'steammax'),
	 (228,'stillus protector'),
	 (390,'suggar'),
	 (148,'suggar'),
	 (20,'taiff'),
	 (234,'taiff'),
	 (147,'tander'),
	 (42,'tany'),
	 (371,'taschibra'),
	 (295,'technicook'),
	 (290,'tedesco'),
	 (110,'tekna'),
	 (177,'therapeutic'),
	 (174,'tiger'),
	 (325,'tocave'),
	 (60,'tork'),
	 (255,'toshiba'),
	 (66,'tramontina'),
	 (86,'trapp'),
	 (248,'tristar'),
	 (109,'tron'),
	 (140,'turbo kin'),
	 (11,'ultra'),
	 (205,'usifaz'),
	 (19,'venti-delta'),
	 (289,'venti sol'),
	 (95,'venti-delta'),
	 (82,'venti-delta'),
	 (225,'ventisilva'),
	 (51,'ventisol'),
	 (285,'ventisul'),
	 (34,'ventura'),
	 (91,'vertix'),
	 (22,'vicini'),
	 (284,'vitalex'),
	 (323,'vithory'),
	 (81,'vonder'),
	 (13,'walita'),
	 (105,'walita philips'),
	 (370,'wanke'),
	 (36,'wanke'),
	 (53,'wap'),
	 (209,'wap prosdocimo'),
	 (347,'weg'),
	 (83,'wesco'),
	 (362,'westinhouse'),
	 (127,'westpress'),
	 (212,'windy'),
	 (160,'wissport'),
	 (221,'wonder'),
	 (321,'xiaomi'),
	 (236,'zagonel'),
	 (373,'zebu'),
	 (299,'zojirushi'),
	 (116,'zonghchan')
)
UPDATE brands b
SET
    brand = ubn.new_name
FROM
    updated_brand_name ubn
WHERE
    b.id = ubn.id;


-- Fix typo corrections on types
WITH updated_type_name (id, new_name) AS (
    VALUES
     (109,'abajur'),
	 (19,'adega'),
	 (309,'adega'),
	 (133,'air fryer'),
	 (17,'air fryer'),
	 (305,'air fryer'),
	 (182,'aparador de cabelo'),
	 (310,'aparador'),
	 (188,'panela de pressão'),
	 (200,'aparador de cabelo'),
	 (57,'aparador de grama'),
	 (343,'aspirador vertical'),
	 (16,'aquecedor'),
	 (127,'aquecedor a óleo'),
	 (131,'aquecedor ambiente'),
	 (226,'ar condicionado'),
	 (5,'aspirador'),
	 (286,'aspirador'),
	 (292,'aspirador'),
	 (99,'aspirador extrator'),
	 (122,'aspirador industrial'),
	 (64,'aspirador portátil'),
	 (266,'aspirador robô'),
	 (267,'aspirador robô'),
	 (147,'aspirador vassourinha'),
	 (282,'aspirador vassourinha'),
	 (249,'aspirador veicular'),
	 (31,'aspirador vertical'),
	 (250,'assadeira elétrica'),
	 (137,'baby lis'),
	 (228,'balloon pump'),
	 (325,'banho maria'),
	 (108,'barbeador'),
	 (115,'base'),
	 (259,'base c/fonte'),
	 (180,'base de aquecimento'),
	 (261,'base de chaleira'),
	 (120,'base de extratora'),
	 (26,'batedeira'),
	 (86,'batedeira de argamassa'),
	 (195,'batedeira planetária'),
	 (82,'batedor de massa'),
	 (205,'bebedouro'),
	 (184,'botão'),
	 (168,'cabo de força'),
	 (163,'cacheador'),
	 (192,'cacheador'),
	 (92,'cafeteira'),
	 (170,'cacheador'),
	 (251,'calicida'),
	 (77,'carcaça do motor de tanquinho'),
	 (172,'carregador'),
	 (207,'carregador de baterias'),
	 (281,'seladora'),
	 (78,'centrifuga'),
	 (97,'centrifuga'),
	 (178,'centrifuga'),
	 (280,'centrifuga'),
	 (24,'centrífuga'),
	 (274,'centrifuga de frutas'),
	 (242,'centrifuga de roupas'),
	 (218,'centrifuga de suco'),
	 (160,'cesto  de lavadora'),
	 (186,'cesto de air fryer'),
	 (158,'cesto do air fryer'),
	 (130,'chaleira elétrica'),
	 (311,'chapa'),
	 (312,'chapa dupla'),
	 (321,'churrasqueira elétrica'),
	 (34,'chuveiro'),
	 (328,'chuveiro'),
	 (66,'cilindro'),
	 (347,'circulador'),
	 (37,'circulador de ar'),
	 (233,'climatizador'),
	 (151,'cobertor térmico'),
	 (210,'compressor de balão'),
	 (155,'cooktop'),
	 (262,'cooktop elétrico'),
	 (341,'cooler box'),
	 (342,'cooler box'),
	 (59,'copo'),
	 (73,'copo de liquidificador'),
	 (202,'cortador de galhos'),
	 (72,'cortador de grama'),
	 (322,'crepera'),
	 (199,'desencapsuladora'),
	 (189,'desumidificador'),
	 (220,'difusor de aromas'),
	 (132,'ducha'),
	 (209,'eixo'),
	 (124,'enceradeira'),
	 (323,'exaustor'),
	 (114,'escova fixa'),
	 (1,'escova rotativa'),
	 (29,'escova secadora'),
	 (123,'esmeril'),
	 (14,'esmerilhadeira'),
	 (145,'esmerilhadeira angular'),
	 (346,'espremedor'),
	 (217,'extensão'),
	 (96,'esterilizador'),
	 (339,'extratora'),
	 (128,'estufa de salgados'),
	 (95,'exaustor'),
	 (121,'espremedor'),
	 (219,'extensão'),
	 (94,'extratora'),
	 (103,'extratora de suco'),
	 (167,'faca elétrica'),
	 (201,'fatiador'),
	 (214,'fero a vapor'),
	 (301,'ferro'),
	 (183,'ferro  seco'),
	 (2,'ferro a vapor'),
	 (3,'ferro a vapor'),
	 (211,'ferro a vapor'),
	 (335,'ferro de viagem'),
	 (25,'ferro seco'),
	 (300,'ferro vaporizador'),
	 (112,'furadeira'),
	 (93,'filtro de linha'),
	 (291,'filtro de água'),
	 (84,'filtro de linha'),
	 (224,'fogão'),
	 (253,'fogão elétrico'),
	 (146,'fonte'),
	 (238,'forninho elétrico'),
	 (337,'forno e air fryer'),
	 (18,'forno elétrico'),
	 (15,'forno elétrico'),
	 (135,'forno elétrico de embutir'),
	 (156,'fresa'),
	 (157,'fritadeira'),
	 (290,'fritadeira com óleo'),
	 (229,'fritadeira elétrica'),
	 (27,'furadeira'),
	 (150,'furadeira'),
	 (190,'furadeira'),
	 (303,'furadeira'),
	 (315,'furadeira'),
	 (46,'furadeira de bancada'),
	 (268,'furadeira'),
	 (173,'furadeira'),
	 (22,'gaveta de air fryer'),
	 (248,'girador de espeto'),
	 (4,'grill'),
	 (212,'grill'),
	 (113,'inalador'),
	 (134,'inalador'),
	 (296,'ini grill'),
	 (70,'iogurteira'),
	 (299,'jarra cafeteira'),
	 (144,'jarra elétrica'),
	 (198,'lavadora'),
	 (213,'lampada'),
	 (43,'lancheira'),
	 (13,'lava e seca'),
	 (49,'lava-louças'),
	 (338,'lava-louças'),
	 (12,'lavadora'),
	 (98,'lavadora'),
	 (275,'lavadora'),
	 (169,'lavadora de pressão'),
	 (152,'lavadora'),
	 (8,'liquidificador'),
	 (206,'liquidificador'),
	 (162,'liquidificador industrial'),
	 (161,'liquidificador industrial'),
	 (76,'lixadeira'),
	 (125,'lixadeira'),
	 (58,'lixadeira de cinta'),
	 (148,'lixadeira de pé'),
	 (36,'lixadeira orbital'),
	 (69,'lixadeira pequena'),
	 (316,'luminária'),
	 (41,'luminária'),
	 (231,'mangueira de passadeira'),
	 (304,'mangueira'),
	 (334,'maquina de gelo'),
	 (265,'maquina de lavar'),
	 (344,'máquina de ozônio'),
	 (345,'maquina de pressão'),
	 (264,'máquina de pressão'),
	 (175,'maquina de sugar leite'),
	 (270,'máquina de vácuo terapia'),
	 (329,'máquina de algodão doce'),
	 (40,'martelete'),
	 (71,'massageador'),
	 (306,'massageador de pernas'),
	 (62,'massageador de pés'),
	 (277,'micro-ondas'),
	 (6,'micro-ondas'),
	 (196,'micro-ondas'),
	 (185,'micro-ondas'),
	 (271,'micro-ondas'),
	 (272,'micro-ondas'),
	 (273,'micro-ondas'),
	 (276,'micro-ondas'),
	 (298,'micro-ondas'),
	 (330,'micro-ondas'),
	 (333,'micro-ondas'),
	 (336,'micro-ondas'),
	 (340,'micro-ondas'),
	 (104,'Micro-ondas de embutir'),
	 (332,'micro-ondas'),
	 (90,'mixer'),
	 (223,'mini lavadora'),
	 (65,'mini retifica'),
	 (294,'micro-ondas'),
	 (227,'misturador'),
	 (136,'mixer'),
	 (256,'mixer'),
	 (257,'mixer'),
	 (159,'modelador de cabelo'),
	 (289,'moedor de café'),
	 (138,'moedor de carne'),
	 (102,'motor'),
	 (110,'motor aparador de grama'),
	 (302,'motor de betoneira'),
	 (142,'mouse'),
	 (116,'multi processador'),
	 (176,'nebulizador'),
	 (191,'nível laser'),
	 (245,'nobreak'),
	 (101,'nv15-6p'),
	 (307,'ventilador de parede'),
	 (235,'odorizador'),
	 (143,'omeleteira'),
	 (181,'painel'),
	 (254,'painel c/ placas'),
	 (313,'painel com placas'),
	 (119,'painel fixo'),
	 (100,'panela de air fryer'),
	 (35,'panela de arroz'),
	 (45,'panela de cera'),
	 (80,'panela de fritadeira'),
	 (44,'panela de pressão'),
	 (297,'panela de pressão elétrica'),
	 (111,'panela elétrica'),
	 (241,'panela elétrica industrial'),
	 (107,'panela wok'),
	 (48,'panificadora'),
	 (141,'panela de arroz'),
	 (216,'panela de pressão'),
	 (60,'parafusadeira'),
	 (187,'passadeira'),
	 (278,'passadeira'),
	 (50,'passadeira a vapor'),
	 (81,'picador de tempero'),
	 (129,'pipoqueira'),
	 (47,'placa de potencia'),
	 (74,'placa de potencia e interface'),
	 (318,'placas lavadora'),
	 (215,'plaina'),
	 (244,'planetária'),
	 (87,'podador de altura elétrico'),
	 (153,'politriz'),
	 (237,'porta de lava e seca'),
	 (23,'prancha'),
	 (285,'prancha'),
	 (204,'pressurizador de bexiga'),
	 (252,'pressurizador/sugador'),
	 (54,'processador'),
	 (55,'processador'),
	 (75,'processador de alimentos'),
	 (324,'purificador de água'),
	 (232,'escova rotativa'),
	 (247,'resistência'),
	 (225,'robô aspirador'),
	 (11,'secador'),
	 (177,'secador'),
	 (284,'secador'),
	 (288,'secador de lavatório'),
	 (9,'secadora'),
	 (269,'secadora de roupas'),
	 (139,'seladora a vácuo'),
	 (263,'separador de cabelo'),
	 (67,'serra circular'),
	 (38,'serra de bancada'),
	 (117,'serra manual'),
	 (83,'serra mármore'),
	 (33,'serra mármore'),
	 (30,'serra tico tico'),
	 (331,'serra tico tico'),
	 (21,'soprador'),
	 (56,'sovadeira de massa'),
	 (236,'tampa'),
	 (91,'tanquinho'),
	 (140,'tanquinho duplo'),
	 (308,'tanque e centrifuga'),
	 (32,'tanquinho'),
	 (326,'televisão'),
	 (327,'televisão'),
	 (51,'termostato de grill'),
	 (118,'tico tico'),
	 (126,'torneira elétrica'),
	 (7,'torradeira'),
	 (203,'tostador'),
	 (240,'transformador'),
	 (179,'retifica'),
	 (52,'triturador'),
	 (208,'triturador de pia'),
	 (260,'triturador de tempero'),
	 (53,'tupia'),
	 (106,'vidro da tampa'),
	 (320,'ultrassom'),
	 (20,'umidificador'),
	 (317,'válvula 4 vias'),
	 (149,'vaporeto portátil'),
	 (63,'vaporeto'),
	 (174,'vaporizador'),
	 (68,'vassourinha'),
	 (165,'ventilador de mesa'),
	 (166,'Ventilador de mesa'),
	 (171,'ventilador de coluna'),
	 (194,'ventilador de parede'),
	 (258,'ventilador de coluna'),
	 (243,'ventilador de mesa'),
	 (164,'ventilador de parede'),
	 (279,'ventilador de teto'),
	 (105,'ventilador de mesa'),
	 (295,'ventilador de parede'),
	 (10,'ventilador'),
	 (287,'ventilador'),
	 (314,'ventilador'),
	 (197,'ventilador  de mesa'),
	 (193,'ventilador de mesa'),
	 (255,'ventilador com garra'),
	 (283,'ventilador de coluna'),
	 (230,'ventilador de chão'),
	 (28,'ventilador de coluna'),
	 (61,'ventilador de coluna'),
	 (85,'ventilador de mesa'),
	 (221,'ventilador de mesa'),
	 (246,'ventilador de mesa'),
	 (42,'ventilador de parede'),
	 (89,'ventilador de parede'),
	 (39,'ventilador de teto'),
	 (79,'ventilador de teto'),
	 (88,'ventilador de parede'),
	 (154,'ventilador pedestal'),
	 (293,'ventilador umidificador'),
	 (239,'ventilador de chão'),
	 (222,'ventilador de chão'),
	 (234,'ventilador de mesa'),
	 (319,'voltímetro')
)
-- Trim and replace spaces on types
UPDATE "types" t 
SET
    "type" = utn.new_name
FROM
    updated_type_name utn
WHERE
    t.id = utn.id;

UPDATE "types"
SET
    "type" = REGEXP_REPLACE(TRIM("type"), '\\s+', ' ', 'g')
WHERE
    "type" <> REGEXP_REPLACE(TRIM("type"), '\\s+', ' ', 'g');

-- Trim and replace spaces on brands
UPDATE brands
SET
    brand = REGEXP_REPLACE(TRIM(brand), '\\s+', ' ', 'g')
WHERE
    brand <> REGEXP_REPLACE(TRIM(brand), '\\s+', ' ', 'g');

-- Trim and replace spaces on models
UPDATE models
SET
    model = REGEXP_REPLACE(TRIM(model), '\\s+', ' ', 'g')
WHERE
    model <> REGEXP_REPLACE(TRIM(model), '\\s+', ' ', 'g');

begin;
-- Remove duplicated values
CREATE TEMP TABLE type_mapping AS
WITH duplicates AS (
    -- Find groups of types duplicates (case insensitive and spaces normalized)
    SELECT 
        REGEXP_REPLACE(TRIM(LOWER(type)), '\\s+', ' ', 'g') as type_lower,
        MIN(id) as keep_id,  -- Oldest ID that will be kept
        ARRAY_AGG(id ORDER BY id) as all_ids  -- All IDs of the group
    FROM types 
    GROUP BY REGEXP_REPLACE(TRIM(LOWER(type)), '\\s+', ' ', 'g')
    HAVING COUNT(*) > 1
),
mapping_data AS (
    -- Create the mapping: each duplicated ID -> ID to be kept
    SELECT 
        unnest(all_ids) as old_id,
        keep_id as new_id,
        type_lower
    FROM duplicates
)
SELECT 
    old_id,
    new_id,
    type_lower,
    CASE WHEN old_id = new_id THEN true ELSE false END as is_keeper
FROM mapping_data;

-- Temporary table to map duplicated IDs BRANDS -> Oldest ID
CREATE TEMP TABLE brand_mapping AS
WITH duplicates AS (
    -- Find groups of brands duplicates (case insensitive and spaces normalized)
    SELECT 
        REGEXP_REPLACE(TRIM(LOWER(brand)), '\\s+', ' ', 'g') as brand_lower,
        MIN(id) as keep_id,  -- Oldest ID that will be kept
        ARRAY_AGG(id ORDER BY id) as all_ids  -- All IDs of the group
    FROM brands 
    GROUP BY REGEXP_REPLACE(TRIM(LOWER(brand)), '\\s+', ' ', 'g')
    HAVING COUNT(*) > 1
),
mapping_data AS (
    -- Create the mapping: each duplicated ID -> ID to be kept
    SELECT 
        unnest(all_ids) as old_id,
        keep_id as new_id,
        brand_lower
    FROM duplicates
)
SELECT 
    old_id,
    new_id,
    brand_lower,
    CASE WHEN old_id = new_id THEN true ELSE false END as is_keeper
FROM mapping_data;

-- Temporary table to map duplicated IDs MODELS -> Oldest ID
CREATE TEMP TABLE model_mapping AS
WITH duplicates AS (
    -- Find groups of models duplicates (case insensitive and spaces normalized)
    SELECT 
        REGEXP_REPLACE(TRIM(LOWER(model)), '\\s+', ' ', 'g') as model_lower,
        MIN(id) as keep_id,  -- Oldest ID that will be kept
        ARRAY_AGG(id ORDER BY id) as all_ids  -- All IDs of the group
    FROM models 
    GROUP BY REGEXP_REPLACE(TRIM(LOWER(model)), '\\s+', ' ', 'g')
    HAVING COUNT(*) > 1
),
mapping_data AS (
    -- Create the mapping: each duplicated ID -> ID to be kept
    SELECT 
        unnest(all_ids) as old_id,
        keep_id as new_id,
        model_lower
    FROM duplicates
)
SELECT 
    old_id,
    new_id,
    model_lower,
    CASE WHEN old_id = new_id THEN true ELSE false END as is_keeper
FROM mapping_data;

-- Update the references of TYPES to point to the oldest ID
UPDATE brands_models_types 
SET id_type = tm.new_id
FROM type_mapping tm
WHERE brands_models_types.id_type = tm.old_id 
  AND NOT tm.is_keeper;

-- Update the references of BRANDS to point to the oldest ID
UPDATE brands_models_types 
SET id_brand = bm.new_id
FROM brand_mapping bm
WHERE brands_models_types.id_brand = bm.old_id 
  AND NOT bm.is_keeper;

-- Update the references of MODELS to point to the oldest ID
UPDATE brands_models_types 
SET id_model = mm.new_id
FROM model_mapping mm
WHERE brands_models_types.id_model = mm.old_id 
  AND NOT mm.is_keeper;


-- Remove the duplicated TYPES (keep only the oldest of each group)
DELETE FROM types 
WHERE id IN (
    SELECT old_id 
    FROM type_mapping 
    WHERE NOT is_keeper
);

-- Remove the duplicated BRANDS (keep only the oldest of each group)
DELETE FROM brands 
WHERE id IN (
    SELECT old_id 
    FROM brand_mapping 
    WHERE NOT is_keeper
);

-- Remove the duplicated MODELS (keep only the oldest of each group)
DELETE FROM models 
WHERE id IN (
    SELECT old_id 
    FROM model_mapping 
    WHERE NOT is_keeper
);

-- Reset the sequences
SELECT setval(pg_get_serial_sequence('types', 'id'), coalesce(MAX(id), 1)) from types;
SELECT setval(pg_get_serial_sequence('brands', 'id'), coalesce(MAX(id), 1)) from brands;
SELECT setval(pg_get_serial_sequence('models', 'id'), coalesce(MAX(id), 1)) from models;
SELECT setval(pg_get_serial_sequence('brands_models_types', 'id'), coalesce(MAX(id), 1)) from brands_models_types;

COMMIT;

drop table type_mapping;
drop table brand_mapping;
drop table model_mapping;