name: Deploy Spring Boot App to Home Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configura acesso SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy no servidor via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            set -e
          
            echo "Accessing project folder"
            cd ~/work_shop_rest_api

            echo "Updating code"
            git pull origin main

            echo "Replacing .env variables"
            cp .env.template .env
            export DB_NAME=${{ secrets.DB_NAME }}
            export DB_USERNAME=${{ secrets.DB_USERNAME }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}

            echo "Updating containers"
            docker compose -f docker-compose-production.yml down
            docker compose -f docker-compose-production.yml up -d --build
          EOF
