name: Deploy Spring Boot App via Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on Home Server
    runs-on: self-hosted

    steps:
      - name: Initial step
        run: |
          echo "Actual directory:"
          pwd
          echo "Folder content:"
          ls -la

      - name: Update local repository
        run: |
          echo "Access project folder"
          cd ~/deploy/workshop_rest_api
          git pull origin main

      - name: Write .env with secrets
        run: |
          cd ~/deploy/workshop_rest_api
          cat > .env <<EOF
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          EOF

      - name: Restart Docker containers
        run: |
          echo "Updating Docker containers"
          cd ~/deploy/workshop_rest_api
          docker compose -f docker-compose-production.yml down || true
          docker compose -f docker-compose-production.yml up -d --build
